name: Terraform
on:
  pull_request:
    paths:
      - "**.tf"
  push:
    branches:
      - main
    paths:
      - "**.tf"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Set up tflint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6.2.1
      - name: Set up trivy
        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514 # v0.2.5
      - name: Run make init
        run: make init
      - name: Run make lint
        run: make lint
